### ISSUE TITLE
gnome 3 and fixed window

### ISSUE THREAD

**Issue by ferrvittorio** [HandBrake/HandBrake-website#1]
Hi,
I encounter troubles reading the status bar while the window is maximised. The last line (% encoding status) is not visible

See two attached screenshots

![schermata del 2016-10-12 14-31-20](https://cloud.githubusercontent.com/assets/7511429/19310151/03fe3df0-9089-11e6-9a9c-14b861b3bb18.png)
![schermata del 2016-10-12 14-31-05](https://cloud.githubusercontent.com/assets/7511429/19310152/0409ad52-9089-11e6-8bf2-2fd796ee3907.png)

**Comment by sr55** [comment]
1. Wrong Repository. This has nothing to do with the HandBrake website.
2. Violation of community Rules. (2c)

Please don't waste our time reposting this.

**Comment by bradleysepos** [comment]
> 2. Violation of community Rules. (2c)

> .WEB-DL.x264.*

To be clear, we have a zero tolerance policy toward this.
