### ISSUE TITLE
Transition away from StartSSL/StartCom/WoSign

### ISSUE THREAD

**Issue by ecnepsnai** [HandBrake/HandBrake-website#2]
Your websites TLS certificate is issued by StartComm, which by many is considered harmful and may eventually be distrusted by operating systems or browsers.

![image](https://cloud.githubusercontent.com/assets/1607109/21167758/9dae2f18-c163-11e6-8dbb-02218d761f92.png)

Firefox has a complete write up of the reasoning behind this: https://docs.google.com/document/d/1C6BlmbeQfn4a9zydVi2UvjBGv6szuSB4sMYUcVrR8vQ/preview

You should move to a different certificate authority, especially one that provides certificate transparency.

Two options are LetsEncrypt and Cloudflare. Both are free.

**Comment by sr55** [comment]
It's something I'm already looking at although I've not had time to complete to fully test yet.

**Comment by sr55** [comment]
I've pushed LetsEncrypt onto our secondary download server since that didn't actually have a SSL cert against it.

https://www.ssllabs.com/ssltest/analyze.html?d=download.handbrake.fr

Assuming we get no issues there, I'll migrate the existing site over to them as well.

**Comment by bradleysepos** [comment]
@sr55 Probably should update our contrib urls to https.

**Comment by sr55** [comment]
@bradleysepos agreed but the server will force the redirect anyway.

**Comment by sr55** [comment]
HSTS now enabled on the main site too, which also brings it A -> A+ on SSL labs.

**Comment by ecnepsnai** [comment]
Good to see people eager to make positive changes with their sites security! 👍 💯

**Comment by sr55** [comment]
After what happened to Transmission, and various other projects. I really don't give it a second thought. If someone spots something wrong or has a suggestion to improve security, it gets fixed.

It's a big part of the reason why ReviewBoard and Trac where shutdown in favour of Github and our Jenkins server is no longer publically accessible.   Keeps the attack surface lower.

**Comment by bradleysepos** [comment]
See https://github.com/HandBrake/HandBrake/commit/5ad6f2b5198d9d034cff49da675c0686a3dacf01

A few third-party hostnames still do not support https, such as Xiph's software and Google's Webm. libxml2 uses ftp (yay). By default, all contribs are fetched from https://download.handbrake.fr, so this is not an issue in practice.

Thanks for reminding us about this, @ecnepsnai.

**Comment by sr55** [comment]
We have hash Checking on the contribs anyway, so it should prevent any issues.

**Comment by bradleysepos** [comment]
Indeed, and I'll be transitioning the hashes from MD5 to SHA256 soon enough. :wink:

**Comment by sr55** [comment]
Transition complete. Both our servers are now on Lets encrypt and get an A+ rating on SSL Labs.

I've put an announcement out on the forum as we will be retiring TLS 1.0 in the next couple of months. This is unfortunatly going to affect a few people but there is not much we can do if they are stuck on old software.

Required for TLS 1.1:

**Desktop**
- Firefox 27
- Chrome 22
- Microsoft Internet Explorer 11
- Microsoft Edge 
- Safari 7 (on OSX 10.9)
- Opera 12.18 

**Devices** 
- Android 5.0
- Windows Phone 8.1 
- Safari 5 on IOS 5
